### ISSUE TITLE
why are some confidence scores greater than 1?

### ISSUE THREAD

**Issue by mrzResearchArena** [bikz05/object-detector#11]
Hi,

Code runs fine but I was confused why the confidence scores for some windows are coming to be greater than 1? I thought confidence scores are always between 0 and 1.

**Comment by gongxijun** [comment]
@mrzResearchArena  i have fix this problem in my fork ,maybe it's will help you 
https://github.com/gongxijun/lantern-detection

**Comment by mrzResearchArena** [comment]
Thank you!
