### ISSUE TITLE
How to train a new module

### ISSUE THREAD

**Issue by SunnerLi** [bikz05/object-detector#3]
Sorry I'm a novice. After I run the test-classifier.py, I got a great result.
Now I want to train the SVM classifier by myself.
I download the UIUC image set that you pose in readme.
Second, I create the pos and neg folder in data/feature folder.
Next, I move the pos- image in TrainImages to pos while neg-image moving to neg image.
So the data folder would like this:

```
sunner@sunnerPC:~/object-detector/data/fetures$ tree .
.
├── neg
│   ├── neg-0.pgm
│   ├── neg-100.pgm
│   ├── .....(skip the middle)
│   └── neg-9.pgm
└── pos
    ├── pos-0.pgm
    ├── pos-100.pgm
    ├── ......(skip the middle)
    └── pos-9.pgm
```

While I run the train-classifier.py, I got several harvest.
the pos and neg folder didn't have *.feat file? So I got empty list in fds and labels.
I change *.feat to *.pgm to meet the format of image set, the console dump with:

```
Traceback (most recent call last):
  File "train-classifier.py", line 31, in <module>
    fd = joblib.load(feat_path)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/numpy_pickle.py", line 462, in load
    obj = unpickler.load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 891, in load_persid
    self.append(self.persistent_load(pid))
AttributeError: NumpyUnpickler instance has no attribute 'persistent_load'
```

Is some step I got wrong? How can I do next? Please give me some advise.

**Comment by SunnerLi** [comment]
I solve the problem by myself...
The first step to train the new module should extract the feature first.
After I run extract-features.py, all is fine in rest.
We don't need to modify the train script file.
Sorry make for some noise.

**Comment by HenryJunW** [comment]
Hello, I got an error saying that 'ValueError: X has 324 features per sample; expecting 2430'. Do you have any idea how to solve it? Thanks in advance.
